### ISSUE TITLE
Bug: Alarm mails are not sent (regression) 

### ISSUE THREAD

**Issue by lemoer** [lemoer/keepitup#14]
This is a regression based on the changes done in #6, #9 or #13.

```
Mär 24 13:26:27 harvester python[16130]: Traceback (most recent call last):
Mär 24 13:26:27 harvester python[16130]:   File "/opt/keepitup/ping_worker.py", line 28, in <module>
Mär 24 13:26:27 harvester python[16130]:     alarm = n.check(session)
Mär 24 13:26:27 harvester python[16130]:   File "/opt/keepitup/main.py", line 342, in check
Mär 24 13:26:27 harvester python[16130]:     alarm.send_notification_mails(session)
Mär 24 13:26:27 harvester python[16130]:   File "/opt/keepitup/main.py", line 255, in send_notification_mails
Mär 24 13:26:27 harvester python[16130]:     mail_template = self.get_mail_template("resolved")
Mär 24 13:26:27 harvester python[16130]: AttributeError: 'Alarm' object has no attribute 'get_mail_template'
```

I am not sure if only "resolved"-Mails are affected. Maybe "problem"-Mails are also affected.

**Comment by lemoer** [comment]
CC: @moridius
