### ISSUE TITLE
Worker crashes sometimes during mail send

### ISSUE THREAD

**Issue by lemoer** [lemoer/keepitup#2]
```
Feb 21 01:15:24 harvester python[2332]: Traceback (most recent call last):
Feb 21 01:15:24 harvester python[2332]:   File "/opt/keepitup/ping_worker.py", line 35, in <module>
Feb 21 01:15:24 harvester python[2332]:     alarm = n.check(session)
Feb 21 01:15:24 harvester python[2332]:   File "/opt/keepitup/main.py", line 446, in check
Feb 21 01:15:24 harvester python[2332]:     alarm.send_notification_mails(session)
Feb 21 01:15:24 harvester python[2332]:   File "/opt/keepitup/main.py", line 284, in send_notification_mails
Feb 21 01:15:24 harvester python[2332]:     self.alarm_mail_msgid = user.send_mail(mail_template, node=node, url=url)
Feb 21 01:15:24 harvester python[2332]:   File "/opt/keepitup/main.py", line 89, in send_mail
Feb 21 01:15:24 harvester python[2332]:     server.sendmail(SMTP_FROM, self.email, mail)
Feb 21 01:15:24 harvester python[2332]:   File "/usr/lib/python3.7/smtplib.py", line 855, in sendmail
Feb 21 01:15:24 harvester python[2332]:     msg = _fix_eols(msg).encode('ascii')
Feb 20 19:02:45 harvester python[2332]: UnicodeEncodeError: 'ascii' codec can't encode character '\xfc' in position 265: ordinal not in range(128)

```

**Comment by lemoer** [comment]
This was recently (today) seen three times with the node "UFU-FWH-Mecklenheidestr-Büro". Most likely this always happens for nodes with umlaute in their names.

**Comment by lemoer** [comment]
CC: @bschelm, @moridius

**Comment by lemoer** [comment]
![Screenshot from 2021-03-12 01-24-40](https://user-images.githubusercontent.com/601153/110873310-c3d19480-82d1-11eb-99ba-d7f12e29b1fc.png)

I think, it should work now :)

**Comment by lemoer** [comment]
CC: @bschelm
